# Use postgres/example user/password credentials
version: "3.1"
name: "transcendance"

services:
  db:
    image: postgres:15-bullseye
    restart: always
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 30s
    #   timeout: 60s
    #   retries: 5
    #   start_period: 80s
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=example
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
      target: development
    ports:
      - 3000:3000
    networks:
      - server-side
      - client-side
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
      target: development
    ports:
      - 5173:5173
    networks:
      - client-side
    # depends_on:
    #   - backend

networks:
  client-side: {}
  server-side: {}

volumes:
  db-data: {}
