# Use postgres/example user/password credentials
version: "3"
name: "transcendance"

services:
  db:
    image: postgres:15-bullseye
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=example
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
      target: development
    ports:
      - 3000:3000
    networks:
      - server-side
      - client-side
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
      target: development
    ports:
      - 5173:5173
    networks:
      - client-side
    depends_on:
      - backend

networks:
  client-side: {}
  server-side: {}

volumes:
  db-data: {}
