# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres:15-bullseye
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: example
    expose:
     - "5432"

  back:
    build: requirements/back
    depends_on:
      - db
    restart: on-failure
    ports:
      - 8080:8080