# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres:15-bullseye
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
     - 5432:5432

  back:
    container_name: back
    stdin_open: true
    build:
      dockerfile: ./requirements/back/Dockerfile
    depends_on:
      - db
    restart: on-failure
    ports:
      - 8080:8080
      - 5555:5555

volumes:
  postgres-data: